openapi: 3.1.0
info:
  description: API for managing user groups in Saviynt.
  title: Saviynt API
  version: 1.0.0
servers:
- description: Sample server
  url: "https://api.example.com"
paths:
  /createUpdateUserGroup:
    post:
      description: "This API create or update usergroup in SSM.\nThe `Authorization`\
        \ must have `Bearer` followed by `Token`.\nMandatory params:\n`usergroup`,\n\
        `username`\nOptional params:\n`user_groupdescription`,\n`users` - \n1. `username`\
        \ (mandatory),\n2. `updateType` - ADD/REMOVE (optional),\n`entitlements` -\
        \ \n1. `endpoint` (mandatory),\n2. `entitlement_type` (mandatory),\n3. `entitlement_value`\
        \ (mandatory),\n4. `updateType` ADD/REMOVE (optional),\n`owners` -\n1. `username`\
        \ (mandatory),\n2. `updateType` - ADD/REMOVE/SETRANK (optional),\n3. `rank`\
        \ (optional)"
      operationId: createUpdateUsergroup
      requestBody:
        content:
          application/json:
            examples:
              Create/Update UserGroup:
                value:
                  entitlements:
                  - endpoint: Oracle
                    entitlement_type: OEBS-Responsibility
                    entitlement_value: FIXED_ASSET_INQUIRY_TECH_IN
                    updateType: ADD
                  - endpoint: Oracle
                    entitlement_type: OEBS-Responsibility
                    entitlement_value: FIXED_ASSET_INQUIRY_SOFT_IN
                    updateType: REMOVE
                  owners:
                  - rank: "2"
                    updateType: ADD
                    username: G000706
                  - updateType: REMOVE
                    username: G000526
                  - rank: "2"
                    updateType: SETRANK
                    username: U009075
                  user_groupdescription: ADOwnerGroupdesc
                  usergroup: ADOwnerGroup
                  username: admin
                  users:
                  - updateType: ADD
                    username: U003961
                  - updateType: REMOVE
                    username: M0014
            schema:
              $ref: '#/components/schemas/createUpdateUsergroup_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                Create/Update UserGroup:
                  value:
                    errorCode: "1"
                    msg: ' user U003961 already present in usergroup. user M0014 does
                      not exist in usergroup. entitlement FIXED_ASSET_INQUIRY_TECH_IN
                      already present in usergroup. entitlement FIXED_ASSET_INQUIRY_SOFT_IN
                      does not exist in usergroup. owner G000706 is already present.
                      Owner U009075 does not exist in usergroup. owner G000526 is
                      not present.'
                    usergroupkey: "2"
              schema:
                $ref: '#/components/schemas/createUpdateUsergroup_200_response'
          description: Create/Update UserGroup
          headers:
            Access-Control-Allow-Credentials:
              explode: false
              schema:
                example: "true"
                type: string
              style: simple
            Access-Control-Allow-Origin:
              explode: false
              schema:
                example: http://localhost
                type: string
              style: simple
            Cache-Control:
              explode: false
              schema:
                example: "post-check=0, pre-check=0"
                type: string
              style: simple
            Date:
              explode: false
              schema:
                example: "Tue, 22 Jun 2021 18:33:36 GMT"
                type: string
              style: simple
            Expires:
              explode: false
              schema:
                example: "Sun, 7 May 1995 12:00:00 GMT"
                type: string
              style: simple
            Referrer-Policy:
              explode: false
              schema:
                example: same-origin
                type: string
              style: simple
            Server:
              explode: false
              schema:
                example: Apache-Coyote/1.1
                type: string
              style: simple
            Set-Cookie:
              explode: false
              schema:
                example: CCSRF-TOKEN=1eae9a2d-290d-44de-bcf9-3d74760832f7; Path=/
                type: string
              style: simple
            Strict-Transport-Security:
              explode: false
              schema:
                example: max-age=31536000; includeSubdomains
                type: string
              style: simple
            X-Content-Type-Options:
              explode: false
              schema:
                example: nosniff
                type: string
              style: simple
            X-Frame-Options:
              explode: false
              schema:
                example: DENY
                type: string
              style: simple
      summary: Create/Update UserGroup
      tags:
      - groups
  /addRemoveUserFromUserGroup:
    post:
      description: "This API is used to add or remove user from a usergroup in SSM\r\
        \n\r\nThe `Authorization` must have `Bearer` followed by `Token`.\r\n\r\n\
        Mandatory params: \r\n\r\n`username` - User which needs to be added/ removed,\r\
        \n\r\n`user_groupname` - Group name to be added/removed,\r\n\t\r\n`actionType`\
        \ (0/1) - 0:Add and 1:Remove"
      operationId: addRemoveUserFromUsergroup
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/addRemoveUserFromUsergroup_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                Add/Remove User From UserGroup:
                  value:
                    errorCode: "0"
                    message: saved successfully
              schema:
                $ref: '#/components/schemas/addRemoveUserFromUsergroup_200_response'
          description: Add/Remove User From UserGroup
          headers:
            Date:
              explode: false
              schema:
                example: "Tue, 11 Sep 2018 01:24:07 GMT"
                type: string
              style: simple
            Server:
              explode: false
              schema:
                example: Apache-Coyote/1.1
                type: string
              style: simple
            Set-Cookie:
              explode: false
              schema:
                example: CCSRF-TOKEN=a3914d7a-7ab2-4354-9de2-4fb0258322f9; Path=/
                type: string
              style: simple
      summary: Add/Remove User From UserGroup
      tags:
      - groups
  /deleteUserGroup:
    post:
      description: |-
        This API delete usergroup in SSM.
        The `Authorization` must have `Bearer` followed by `Token`.
        Mandatory params:
        `username`,
        `usergroup`
      operationId: deleteUsergroup
      requestBody:
        content:
          application/json:
            examples:
              Delete UserGroup:
                value:
                  usergroup: testApi2
                  username: smarquez
            schema:
              $ref: '#/components/schemas/deleteUsergroup_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                Delete UserGroup:
                  value:
                    errorCode: "0"
                    msg: Success
              schema:
                $ref: '#/components/schemas/deleteUsergroup_200_response'
          description: Delete UserGroup
          headers:
            Date:
              explode: false
              schema:
                example: "Sat, 29 Dec 2018 01:43:15 GMT"
                type: string
              style: simple
            Server:
              explode: false
              schema:
                example: Apache-Coyote/1.1
                type: string
              style: simple
            Set-Cookie:
              explode: false
              schema:
                example: CCSRF-TOKEN=4df14cd0-0217-4b9e-8908-99c221e39ede; Path=/
                type: string
              style: simple
            X-Content-Type-Options:
              explode: false
              schema:
                example: nosniff
                type: string
              style: simple
      summary: Delete UserGroup
      tags:
      - groups
  /fetchUserGroup:
    post:
      description: |-
        This API returns list of UserGroups in SSM.
        The `Authorization` must have `Bearer` followed by `Token`.
        Optional params:
        `usergroupkey`,
        `usergroupname`,
        `usergroupdescription`,`groupid`,
        `max (default value is 5)`,
        `offset (default value is 0)`
      operationId: getListOfUsergroups
      parameters:
      - explode: true
        in: query
        name: systemname
        required: false
        schema:
          example: amigopod
          type: string
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          example: "0"
          type: string
        style: form
      - explode: true
        in: query
        name: connectionname
        required: false
        schema:
          example: CN_SERP_ECC_A53
          type: string
        style: form
      - explode: true
        in: query
        name: connectionType
        required: false
        schema:
          example: SAP
          type: string
        style: form
      requestBody:
        content:
          application/json:
            examples:
              Get List of UserGroups:
                value:
                  usergroupkey: "1"
                  usergroupname: AdminGroup
            schema:
              $ref: '#/components/schemas/getListOfUsergroups_request'
      responses:
        "200":
          content:
            application/json:
              examples:
                Fetch UserGroups - SUCCESS:
                  value:
                    displaycount: 1
                    errorcode: 0
                    msg: success
                    totalcount: 1
                    usergroups:
                    - entitlements:
                      - description: ""
                        displayname: ""
                        entitlement_value: Report Writer (Report_Writer)
                        entitlement_valuekey: 1
                      - description: ""
                        displayname: ""
                        entitlement_value: Job and Position Administrator (Job_and_Position_Administrator)
                        entitlement_valuekey: 2
                      - description: ""
                        displayname: ""
                        entitlement_value: Organization Administrator (Organization_Administrator)
                        entitlement_valuekey: 3
                      - description: ""
                        displayname: ""
                        entitlement_value: Setup Administrator (Setup_Administrator)
                        entitlement_valuekey: 4
                      - description: ""
                        displayname: ""
                        entitlement_value: Compensation Administrator (Compensation_Administrator)
                        entitlement_valuekey: 5
                      - description: ""
                        displayname: ""
                        entitlement_value: Benefits Administrator (Benefits_Administrator)
                        entitlement_valuekey: 6
                      - description: ""
                        displayname: ""
                        entitlement_value: Payroll Interface Administrator (Payroll_Interface_Administrator)
                        entitlement_valuekey: 7
                      - description: ""
                        displayname: ""
                        entitlement_value: Costing Administrator (Costing_Administrator)
                        entitlement_valuekey: 8
                      - description: ""
                        displayname: ""
                        entitlement_value: Training Administrator (Inactive) (Training_Administrator)
                        entitlement_valuekey: 9
                      - description: ""
                        displayname: ""
                        entitlement_value: Talent Administrator (Employee_Review_Administrator)
                        entitlement_valuekey: 10
                      - description: ""
                        displayname: ""
                        entitlement_value: Business Process Administrator (Business_Process_Administrator)
                        entitlement_valuekey: 11
                      - description: ""
                        displayname: ""
                        entitlement_value: Finance Administrator (Finance_Administrator)
                        entitlement_valuekey: 12
                      - description: ""
                        displayname: ""
                        entitlement_value: Customer Administrator (Customer_Administrator)
                        entitlement_valuekey: 13
                      groupid: ""
                      owners: []
                      risk: ""
                      user_groupdescription: USERAPPROVAL
                      user_groupname: USERAPPROVAL
                      usergroupkey: 1
                      users:
                      - city: ""
                        email: ""
                        firstname: adminfname
                        lastname: adminlname
                        userkey: 1
                        username: admin
                      - city: San Francisco
                        email: lmcneil@workday.net
                        firstname: Logan
                        lastname: McNeil
                        userkey: 12444
                        username: lmcneil
                      - city: San Francisco
                        email: smorgan@workday.net
                        firstname: Steve
                        lastname: Morgan
                        userkey: 12445
                        username: smorgan
                      - city: San Francisco
                        email: oliverr@sav.net
                        firstname: Oliver
                        lastname: Reynolds
                        userkey: 12446
                        username: Executive Management
                Get List of UserGroups - usergroupkey:
                  value:
                    displaycount: 1
                    errorcode: 0
                    msg: success
                    totalcount: 1
                    usergroups:
                    - entitlements:
                      - description: Fixed Assets Inquiry - Tech IN
                        displayname: ""
                        entitlement_value: FIXED_ASSET_INQUIRY_TECH_IN
                        entitlement_valuekey: 3
                      groupid: ""
                      owners:
                      - city: ""
                        comments: ""
                        email: example@saviynt.com
                        firstname: Lilith
                        lastname: Larionova
                        rank: 1
                        userkey: 301254
                        username: zz003487
                      risk: ""
                      user_groupdescription: Group admin
                      user_groupname: AdminGroup
                      usergroupkey: 1
                      users:
                      - city: Los Angeles
                        email: example@saviynt.com
                        firstname: margar'etm-anager
                        lastname: margaretm'a:nager
                        userkey: 317375
                        username: margaret'manager
                      - city: Los Angeles
                        email: example@saviynt.com
                        firstname: Stacy
                        lastname: Sponsor
                        userkey: 317378
                        username: stacysponsor
              schema:
                $ref: '#/components/schemas/getListOfUsergroups_200_response'
          description: Fetch UserGroups - SUCCESS / Get List of UserGroups - usergroupkey
          headers:
            Access-Control-Allow-Credentials:
              explode: false
              schema:
                example: "true"
                type: string
              style: simple
            Access-Control-Allow-Origin:
              explode: false
              schema:
                example: http://localhost
                type: string
              style: simple
            Cache-Control:
              explode: false
              schema:
                example: "post-check=0, pre-check=0"
                type: string
              style: simple
            Date:
              explode: false
              schema:
                example: "Tue, 22 Jun 2021 18:08:29 GMT"
                type: string
              style: simple
            Expires:
              explode: false
              schema:
                example: "Sun, 7 May 1995 12:00:00 GMT"
                type: string
              style: simple
            Referrer-Policy:
              explode: false
              schema:
                example: same-origin
                type: string
              style: simple
            Server:
              explode: false
              schema:
                example: Apache-Coyote/1.1
                type: string
              style: simple
            Set-Cookie:
              explode: false
              schema:
                example: CCSRF-TOKEN=1eae9a2d-290d-44de-bcf9-3d74760832f7; Path=/
                type: string
              style: simple
            Strict-Transport-Security:
              explode: false
              schema:
                example: max-age=31536000; includeSubdomains
                type: string
              style: simple
            X-Content-Type-Options:
              explode: false
              schema:
                example: nosniff
                type: string
              style: simple
            X-Frame-Options:
              explode: false
              schema:
                example: DENY
                type: string
              style: simple
        "412":
          content:
            application/json:
              examples:
                Get List of UserGroups - FAIL:
                  value:
                    errorcode: 1
                    msg: user group not found  with groupid 100
              schema:
                $ref: '#/components/schemas/getListOfUsergroups_412_response'
          description: Get List of UserGroups - FAIL
          headers:
            Access-Control-Allow-Credentials:
              explode: false
              schema:
                example: "true"
                type: string
              style: simple
            Access-Control-Allow-Origin:
              explode: false
              schema:
                example: http://localhost
                type: string
              style: simple
            Cache-Control:
              explode: false
              schema:
                example: "post-check=0, pre-check=0"
                type: string
              style: simple
            Date:
              explode: false
              schema:
                example: "Mon, 15 Jun 2020 20:52:09 GMT"
                type: string
              style: simple
            Expires:
              explode: false
              schema:
                example: "Sun, 7 May 1995 12:00:00 GMT"
                type: string
              style: simple
            Referrer-Policy:
              explode: false
              schema:
                example: same-origin
                type: string
              style: simple
            Server:
              explode: false
              schema:
                example: Apache-Coyote/1.1
                type: string
              style: simple
            Set-Cookie:
              explode: false
              schema:
                example: CCSRF-TOKEN=dd76fe8b-d8b4-4f34-9f59-e87d073dceb4; Path=/
                type: string
              style: simple
            Strict-Transport-Security:
              explode: false
              schema:
                example: max-age=31536000; includeSubdomains
                type: string
              style: simple
            X-Content-Type-Options:
              explode: false
              schema:
                example: nosniff
                type: string
              style: simple
            X-Frame-Options:
              explode: false
              schema:
                example: DENY
                type: string
              style: simple
      summary: Get List of UserGroups
      tags:
      - groups
components:
  schemas:
    createUpdateUsergroup_request:
      properties:
        entitlements:
          example:
          - endpoint: Oracle
            entitlement_type: OEBS-Responsibility
            entitlement_value: FIXED_ASSET_INQUIRY_TECH_IN
            updateType: ADD
          - endpoint: Oracle
            entitlement_type: OEBS-Responsibility
            entitlement_value: FIXED_ASSET_INQUIRY_SOFT_IN
            updateType: REMOVE
          items:
            $ref: '#/components/schemas/createUpdateUsergroup_request_entitlements_inner'
          type: array
        owners:
          example:
          - rank: "2"
            updateType: ADD
            username: G000706
          - updateType: REMOVE
            username: G000526
          - rank: "2"
            updateType: SETRANK
            username: U009075
          items:
            $ref: '#/components/schemas/createUpdateUsergroup_request_owners_inner'
          type: array
        user_groupdescription:
          example: ADOwnerGroupdesc
          type: string
        usergroup:
          example: ADOwnerGroup
          type: string
        username:
          example: admin
          type: string
        users:
          example:
          - updateType: ADD
            username: U003961
          - updateType: REMOVE
            username: M0014
          items:
            $ref: '#/components/schemas/createUpdateUsergroup_request_users_inner'
          type: array
    getListOfUsergroups_200_response_usergroups_inner:
      properties:
        entitlements:
          example:
          - description: ""
            displayname: ""
            entitlement_value: Report Writer (Report_Writer)
            entitlement_valuekey: 1
          - description: ""
            displayname: ""
            entitlement_value: Job and Position Administrator (Job_and_Position_Administrator)
            entitlement_valuekey: 2
          - description: ""
            displayname: ""
            entitlement_value: Organization Administrator (Organization_Administrator)
            entitlement_valuekey: 3
          - description: ""
            displayname: ""
            entitlement_value: Setup Administrator (Setup_Administrator)
            entitlement_valuekey: 4
          - description: ""
            displayname: ""
            entitlement_value: Compensation Administrator (Compensation_Administrator)
            entitlement_valuekey: 5
          - description: ""
            displayname: ""
            entitlement_value: Benefits Administrator (Benefits_Administrator)
            entitlement_valuekey: 6
          - description: ""
            displayname: ""
            entitlement_value: Payroll Interface Administrator (Payroll_Interface_Administrator)
            entitlement_valuekey: 7
          - description: ""
            displayname: ""
            entitlement_value: Costing Administrator (Costing_Administrator)
            entitlement_valuekey: 8
          - description: ""
            displayname: ""
            entitlement_value: Training Administrator (Inactive) (Training_Administrator)
            entitlement_valuekey: 9
          - description: ""
            displayname: ""
            entitlement_value: Talent Administrator (Employee_Review_Administrator)
            entitlement_valuekey: 10
          - description: ""
            displayname: ""
            entitlement_value: Business Process Administrator (Business_Process_Administrator)
            entitlement_valuekey: 11
          - description: ""
            displayname: ""
            entitlement_value: Finance Administrator (Finance_Administrator)
            entitlement_valuekey: 12
          - description: ""
            displayname: ""
            entitlement_value: Customer Administrator (Customer_Administrator)
            entitlement_valuekey: 13
          items:
            $ref: '#/components/schemas/getListOfUsergroups_200_response_usergroups_inner_entitlements_inner'
          type: array
        groupid:
          example: ""
          type: string
        owners:
          example: []
          items: {}
          type: array
        risk:
          example: ""
          type: string
        user_groupdescription:
          example: USERAPPROVAL
          type: string
        user_groupname:
          example: USERAPPROVAL
          type: string
        usergroupkey:
          example: 1
          type: number
        users:
          example:
          - city: ""
            email: ""
            firstname: adminfname
            lastname: adminlname
            userkey: 1
            username: admin
          - city: San Francisco
            email: lmcneil@workday.net
            firstname: Logan
            lastname: McNeil
            userkey: 12444
            username: lmcneil
          - city: San Francisco
            email: smorgan@workday.net
            firstname: Steve
            lastname: Morgan
            userkey: 12445
            username: smorgan
          - city: San Francisco
            email: oliverr@sav.net
            firstname: Oliver
            lastname: Reynolds
            userkey: 12446
            username: Executive Management
          items:
            $ref: '#/components/schemas/getListOfUsergroups_200_response_usergroups_inner_users_inner'
          type: array
    deleteUsergroup_200_response:
      example:
        msg: Success
        errorCode: "0"
      properties:
        errorCode:
          example: "0"
          type: string
        msg:
          example: Success
          type: string
    getListOfUsergroups_412_response:
      example:
        msg: user group not found  with groupid 100
        errorcode: 1
      properties:
        errorcode:
          example: 1
          type: number
        msg:
          example: user group not found  with groupid 100
          type: string
    getListOfUsergroups_request:
      properties:
        usergroupkey:
          example: "1"
          type: string
        usergroupname:
          example: AdminGroup
          type: string
    getListOfUsergroups_200_response_usergroups_inner_entitlements_inner:
      properties:
        description:
          example: ""
          type: string
        displayname:
          example: ""
          type: string
        entitlement_value:
          example: Report Writer (Report_Writer)
          type: string
        entitlement_valuekey:
          example: 1
          type: number
    createUpdateUsergroup_request_owners_inner:
      properties:
        rank:
          example: "2"
          type: string
        updateType:
          example: ADD
          type: string
        username:
          example: G000706
          type: string
    createUpdateUsergroup_200_response:
      example:
        msg: ' user U003961 already present in usergroup. user M0014 does not exist
          in usergroup. entitlement FIXED_ASSET_INQUIRY_TECH_IN already present in
          usergroup. entitlement FIXED_ASSET_INQUIRY_SOFT_IN does not exist in usergroup.
          owner G000706 is already present. Owner U009075 does not exist in usergroup.
          owner G000526 is not present.'
        usergroupkey: "2"
        errorCode: "1"
      properties:
        errorCode:
          example: "1"
          type: string
        msg:
          example: ' user U003961 already present in usergroup. user M0014 does not
            exist in usergroup. entitlement FIXED_ASSET_INQUIRY_TECH_IN already present
            in usergroup. entitlement FIXED_ASSET_INQUIRY_SOFT_IN does not exist in
            usergroup. owner G000706 is already present. Owner U009075 does not exist
            in usergroup. owner G000526 is not present.'
          type: string
        usergroupkey:
          example: "2"
          type: string
    addRemoveUserFromUsergroup_200_response:
      example:
        errorCode: "0"
        message: saved successfully
      properties:
        errorCode:
          example: "0"
          type: string
        message:
          example: saved successfully
          type: string
    getListOfUsergroups_200_response_usergroups_inner_users_inner:
      properties:
        city:
          example: ""
          type: string
        email:
          example: ""
          type: string
        firstname:
          example: adminfname
          type: string
        lastname:
          example: adminlname
          type: string
        userkey:
          example: 1
          type: number
        username:
          example: admin
          type: string
    deleteUsergroup_request:
      properties:
        usergroup:
          example: testApi2
          type: string
        username:
          example: smarquez
          type: string
    createUpdateUsergroup_request_entitlements_inner:
      properties:
        endpoint:
          example: Oracle
          type: string
        entitlement_type:
          example: OEBS-Responsibility
          type: string
        entitlement_value:
          example: FIXED_ASSET_INQUIRY_TECH_IN
          type: string
        updateType:
          example: ADD
          type: string
    createUpdateUsergroup_request_users_inner:
      properties:
        updateType:
          example: ADD
          type: string
        username:
          example: U003961
          type: string
    addRemoveUserFromUsergroup_request:
      properties:
        actionType:
          example: "0"
          type: string
        user_groupname:
          example: TEST USER GROUP
          type: string
        username:
          example: bharell
          type: string
    getListOfUsergroups_200_response:
      example:
        displaycount: 1
        msg: success
        totalcount: 1
        usergroups:
        - entitlements:
          - description: ""
            displayname: ""
            entitlement_value: Report Writer (Report_Writer)
            entitlement_valuekey: 1
          - description: ""
            displayname: ""
            entitlement_value: Job and Position Administrator (Job_and_Position_Administrator)
            entitlement_valuekey: 2
          - description: ""
            displayname: ""
            entitlement_value: Organization Administrator (Organization_Administrator)
            entitlement_valuekey: 3
          - description: ""
            displayname: ""
            entitlement_value: Setup Administrator (Setup_Administrator)
            entitlement_valuekey: 4
          - description: ""
            displayname: ""
            entitlement_value: Compensation Administrator (Compensation_Administrator)
            entitlement_valuekey: 5
          - description: ""
            displayname: ""
            entitlement_value: Benefits Administrator (Benefits_Administrator)
            entitlement_valuekey: 6
          - description: ""
            displayname: ""
            entitlement_value: Payroll Interface Administrator (Payroll_Interface_Administrator)
            entitlement_valuekey: 7
          - description: ""
            displayname: ""
            entitlement_value: Costing Administrator (Costing_Administrator)
            entitlement_valuekey: 8
          - description: ""
            displayname: ""
            entitlement_value: Training Administrator (Inactive) (Training_Administrator)
            entitlement_valuekey: 9
          - description: ""
            displayname: ""
            entitlement_value: Talent Administrator (Employee_Review_Administrator)
            entitlement_valuekey: 10
          - description: ""
            displayname: ""
            entitlement_value: Business Process Administrator (Business_Process_Administrator)
            entitlement_valuekey: 11
          - description: ""
            displayname: ""
            entitlement_value: Finance Administrator (Finance_Administrator)
            entitlement_valuekey: 12
          - description: ""
            displayname: ""
            entitlement_value: Customer Administrator (Customer_Administrator)
            entitlement_valuekey: 13
          groupid: ""
          owners: []
          risk: ""
          user_groupdescription: USERAPPROVAL
          user_groupname: USERAPPROVAL
          usergroupkey: 1
          users:
          - city: ""
            email: ""
            firstname: adminfname
            lastname: adminlname
            userkey: 1
            username: admin
          - city: San Francisco
            email: lmcneil@workday.net
            firstname: Logan
            lastname: McNeil
            userkey: 12444
            username: lmcneil
          - city: San Francisco
            email: smorgan@workday.net
            firstname: Steve
            lastname: Morgan
            userkey: 12445
            username: smorgan
          - city: San Francisco
            email: oliverr@sav.net
            firstname: Oliver
            lastname: Reynolds
            userkey: 12446
            username: Executive Management
        errorcode: 0
      properties:
        displaycount:
          example: 1
          type: number
        errorcode:
          example: 0
          type: number
        msg:
          example: success
          type: string
        totalcount:
          example: 1
          type: number
        usergroups:
          example:
          - entitlements:
            - description: ""
              displayname: ""
              entitlement_value: Report Writer (Report_Writer)
              entitlement_valuekey: 1
            - description: ""
              displayname: ""
              entitlement_value: Job and Position Administrator (Job_and_Position_Administrator)
              entitlement_valuekey: 2
            - description: ""
              displayname: ""
              entitlement_value: Organization Administrator (Organization_Administrator)
              entitlement_valuekey: 3
            - description: ""
              displayname: ""
              entitlement_value: Setup Administrator (Setup_Administrator)
              entitlement_valuekey: 4
            - description: ""
              displayname: ""
              entitlement_value: Compensation Administrator (Compensation_Administrator)
              entitlement_valuekey: 5
            - description: ""
              displayname: ""
              entitlement_value: Benefits Administrator (Benefits_Administrator)
              entitlement_valuekey: 6
            - description: ""
              displayname: ""
              entitlement_value: Payroll Interface Administrator (Payroll_Interface_Administrator)
              entitlement_valuekey: 7
            - description: ""
              displayname: ""
              entitlement_value: Costing Administrator (Costing_Administrator)
              entitlement_valuekey: 8
            - description: ""
              displayname: ""
              entitlement_value: Training Administrator (Inactive) (Training_Administrator)
              entitlement_valuekey: 9
            - description: ""
              displayname: ""
              entitlement_value: Talent Administrator (Employee_Review_Administrator)
              entitlement_valuekey: 10
            - description: ""
              displayname: ""
              entitlement_value: Business Process Administrator (Business_Process_Administrator)
              entitlement_valuekey: 11
            - description: ""
              displayname: ""
              entitlement_value: Finance Administrator (Finance_Administrator)
              entitlement_valuekey: 12
            - description: ""
              displayname: ""
              entitlement_value: Customer Administrator (Customer_Administrator)
              entitlement_valuekey: 13
            groupid: ""
            owners: []
            risk: ""
            user_groupdescription: USERAPPROVAL
            user_groupname: USERAPPROVAL
            usergroupkey: 1
            users:
            - city: ""
              email: ""
              firstname: adminfname
              lastname: adminlname
              userkey: 1
              username: admin
            - city: San Francisco
              email: lmcneil@workday.net
              firstname: Logan
              lastname: McNeil
              userkey: 12444
              username: lmcneil
            - city: San Francisco
              email: smorgan@workday.net
              firstname: Steve
              lastname: Morgan
              userkey: 12445
              username: smorgan
            - city: San Francisco
              email: oliverr@sav.net
              firstname: Oliver
              lastname: Reynolds
              userkey: 12446
              username: Executive Management
          items:
            $ref: '#/components/schemas/getListOfUsergroups_200_response_usergroups_inner'
          type: array
