openapi: 3.1.0
info:
  contact:
    email: https://github.com/saviynt
    name: Saviynt Developers Team
  description: Deglated Administration
  title: Saviynt Delegated Administration API
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Delegated Administration
paths:
  /ECM/api/v5/getDelegateUserList:
    get:
      description: This API returns list of users that are allowed to be added as
        delegate for a parentuser in SSM.
      operationId: getDelegateUserList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDelegateUserListRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDelegateUserListResponse'
          description: OK
      security:
      - bearerAuth: []
      summary: Get Delegate User List
      tags:
      - Delegated Administration
  /ECM/api/v5/fetchDelegatesList:
    post:
      description: This API is used to retrieve the list of existing delegates and
        their details. If any optional parameter is not specified then only active
        delegates are displayed.
      operationId: fetchExistingDelegatesList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchExistingDelegatesListRequest'
        description: ""
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchExistingDelegatesListResponse'
          description: OK
      security:
      - bearerAuth: []
      summary: Fetch Existing Delegates List
      tags:
      - Delegated Administration
  /ECM/api/v5/createDelegate:
    post:
      description: This method creates a new delegate for a parent User. The input
        parameters of this method contains the details of the Parent User as well
        as the one to whom the Delegation is carried out.
      operationId: createDelegate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDelegateRequest'
        description: ""
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDelegateResponse'
          description: OK
      security:
      - bearerAuth: []
      summary: Create Delegate
      tags:
      - Delegated Administration
  /ECM/api/v5/editDelegate:
    post:
      description: This method is used to edit a specific delegate. The input parameters
        of this method contain the details of the Parent User as well as the one to
        whom the Delegation is carried out.
      operationId: editDelegate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditDelegateRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
      security:
      - bearerAuth: []
      summary: Edit Delegate
      tags:
      - Delegated Administration
  /ECM/api/v5/deleteDelegate:
    post:
      description: This API is used to delete a specific delegate.
      operationId: deleteDelegate
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DeleteDelegateRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
      security:
      - bearerAuth: []
      summary: Delete Delegate
      tags:
      - Delegated Administration
components:
  schemas:
    GetDelegateUserListRequest:
      example:
        offset: 6
        max: 0
        searchCriteria: searchCriteria
        parentusername: parentusername
      properties:
        parentusername:
          type: string
          x-stoplight:
            id: nua9g1y9exw77
        max:
          type: integer
          x-stoplight:
            id: l0vdpd8sm35pv
        offset:
          type: integer
          x-stoplight:
            id: e1y1qosrnhxbg
        searchCriteria:
          description: example "t*" or "te" or "test" to search in username or firstname
            or lastname for the delegate user
          type: string
          x-stoplight:
            id: o7lumu6vnp1zf
      required:
      - parentusername
      title: GetDelegateUserListRequest
      x-stoplight:
        id: vpqc1aeip3unw
    GetDelegateUserListResponse:
      example:
        result:
        - firstname: firstname
          lastname: lastname
          username: username
        - firstname: firstname
          lastname: lastname
          username: username
        msg: msg
        displayCount: displayCount
        errorCode: errorCode
        totalCount: totalCount
      properties:
        result:
          items:
            $ref: '#/components/schemas/DelegateUser'
          type: array
          x-stoplight:
            id: mj1odjmtfuac8
        msg:
          type: string
          x-stoplight:
            id: hfqdwub8svmvd
        displayCount:
          type: string
          x-stoplight:
            id: sdwaxoeyw0ub6
        errorCode:
          type: string
          x-stoplight:
            id: da0skyxhruzld
        totalCount:
          type: string
          x-stoplight:
            id: lxoew67pqc6f2
      title: GetDelegateUserListResponse
      x-stoplight:
        id: cw443dnw8ly41
    CreateDelegateRequest:
      example:
        name: name
        description: description
        delegateenddate: delegateenddate
        delegateusername: delegateusername
        userName: userName
        delegatestartdate: delegatestartdate
        parentusername: parentusername
      properties:
        userName:
          description: this is user who is creating the delegation
          type: string
          x-stoplight:
            id: crkmqc783f671
        name:
          description: name of delegate.
          type: string
          x-stoplight:
            id: a76jr4ozrl1m4
        delegateusername:
          description: This is the user who should be assigned as the delegate of
            the parent user. It must match `username` in `GetDelegateUserList` API
            response.
          type: string
          x-stoplight:
            id: vzezs3yglrcbi
        delegatestartdate:
          description: in format MMDDYYYY
          type: string
          x-stoplight:
            id: d1whomrq2rx8e
        delegateenddate:
          description: in format MMDDYYYY
          type: string
          x-stoplight:
            id: r2d2t9ketxoee
        parentusername:
          description: "this is the parent username, if not passed it will consider\
            \ `userName` as parentusername"
          type: string
          x-stoplight:
            id: isjdqzs6dx7qk
        description:
          type: string
          x-stoplight:
            id: 8b3lt6r1hlfyq
      required:
      - delegateenddate
      - delegatestartdate
      - delegateusername
      - name
      - userName
      title: CreateDelegateRequest
      x-stoplight:
        id: 3loxtkwxpp2q2
    DelegateUser:
      example:
        firstname: firstname
        lastname: lastname
        username: username
      properties:
        firstname:
          type: string
          x-stoplight:
            id: s6bfbv2e0x8r7
        lastname:
          type: string
          x-stoplight:
            id: 6pac6s1vzrobw
        username:
          description: This value is used in the `createDelegate` API.
          type: string
          x-stoplight:
            id: miwr2qeqxhofr
      required:
      - firstname
      - lastname
      - username
      title: DelegateUser
      x-stoplight:
        id: 8q5oto3vw02aq
    CreateDelegateResponse:
      example:
        msg: msg
        delegatekey: delegatekey
        errorCode: errorCode
      properties:
        msg:
          type: string
          x-stoplight:
            id: cy2ccy2bon9xt
        delegatekey:
          type: string
          x-stoplight:
            id: o1ks5a4u2un4v
        errorCode:
          type: string
          x-stoplight:
            id: 7jsbk17c231ua
      required:
      - errorCode
      - msg
      title: CreateDelegateResponse
      x-stoplight:
        id: vqand6dgyglet
    DeleteDelegateRequest:
      properties:
        userName:
          description: this is the user who is deleting the delegate
          type: string
          x-stoplight:
            id: mffcamvadscwu
        key:
          description: the is the delegatekey
          type: string
          x-stoplight:
            id: b57khz3q7au1g
      required:
      - key
      - userName
      title: DeleteDelegateRequest
      x-stoplight:
        id: 2xz3g64u4cg35
    FetchExistingDelegatesListRequest:
      example:
        offset: 6
        max: 0
        userName: userName
        status: ACTIVE
      properties:
        userName:
          description: this is the parentusername
          type: string
          x-stoplight:
            id: 36tid2febza2x
        max:
          type: integer
          x-stoplight:
            id: i8mqep5s7fsh8
        offset:
          type: integer
          x-stoplight:
            id: e13vah1wuz5u7
        status:
          description: values can be ACTIVE / INACTIVE
          enum:
          - ACTIVE
          - INACTIVE
          type: string
          x-stoplight:
            id: yhodygv8v5srk
      required:
      - userName
      title: FetchDelegatesListRequest
      x-stoplight:
        id: 3vp1pbxoxnha7
    Delegate:
      description: Delegate represents a Deleate returne dfrom the Fetch Eisting Delegates
        List API.
      example:
        parentFirstName: parentFirstName
        delegateFirstName: delegateFirstName
        enddate: enddate
        parentLastName: parentLastName
        delegatekey: delegatekey
        delegateLastName: delegateLastName
        name: name
        description: description
        delegateusername: delegateusername
        startdate: startdate
        parentusername: parentusername
        status: ACTIVE
      properties:
        delegatekey:
          type: string
        name:
          type: string
        description:
          type: string
        parentusername:
          type: string
        parentFirstName:
          type: string
        parentLastName:
          type: string
        delegateFirstName:
          type: string
        delegateLastName:
          type: string
        status:
          enum:
          - ACTIVE
          - INACTIVE
          type: string
        delegateusername:
          type: string
        startdate:
          description: date format 07/14/2020
          type: string
        enddate:
          description: date with format 07/14/2020
          type: string
      required:
      - delegatekey
      - delegateusername
      - description
      - enddate
      - name
      - parentusername
      - startdate
      - status
      x-examples:
        Example 1:
          delegatekey: "1"
          name: delegatetest
          description: ""
          parentusername: U013053
          parentFirstName: Maureen
          parentLastName: Knauber
          delegateFirstName: Daniel
          delegateLastName: Schibler
          status: ACTIVE
          delegateusername: U011556
          startdate: 07/14/2020
          enddate: 08/18/2020
    Response:
      example:
        msg: msg
        errorCode: errorCode
      properties:
        msg:
          type: string
          x-stoplight:
            id: hj8ij8k8u90da
        errorCode:
          type: string
          x-stoplight:
            id: wf376c67qe5h6
      required:
      - errorCode
      - msg
      title: Response
      x-stoplight:
        id: zd7zr47c75zkz
    FetchExistingDelegatesListResponse:
      example:
        msg: msg
        delegateList:
        - parentFirstName: parentFirstName
          delegateFirstName: delegateFirstName
          enddate: enddate
          parentLastName: parentLastName
          delegatekey: delegatekey
          delegateLastName: delegateLastName
          name: name
          description: description
          delegateusername: delegateusername
          startdate: startdate
          parentusername: parentusername
          status: ACTIVE
        - parentFirstName: parentFirstName
          delegateFirstName: delegateFirstName
          enddate: enddate
          parentLastName: parentLastName
          delegatekey: delegatekey
          delegateLastName: delegateLastName
          name: name
          description: description
          delegateusername: delegateusername
          startdate: startdate
          parentusername: parentusername
          status: ACTIVE
        errorCode: errorCode
        totalCount: totalCount
        delegateCount: 0
      properties:
        delegateList:
          items:
            $ref: '#/components/schemas/Delegate'
          type: array
          x-stoplight:
            id: ouxs7d2smf6s2
        msg:
          type: string
          x-stoplight:
            id: 9gb768at9zs11
        errorCode:
          type: string
          x-stoplight:
            id: 52vigy54bcfwh
        totalCount:
          type: string
          x-stoplight:
            id: lx6kmumhnzpk3
        delegateCount:
          type: integer
          x-stoplight:
            id: ol8319l5zv6pm
      required:
      - delegateList
      - errorCode
      - msg
      title: FetchDelegatesListResponse
      x-stoplight:
        id: 7w1uzfkcq72d4
    EditDelegateRequest:
      example:
        name: name
        description: description
        delegateenddate: delegateenddate
        delegateusername: delegateusername
        userName: userName
        delegatestartdate: delegatestartdate
        key: key
        parentusername: parentusername
      properties:
        key:
          description: this is the delegatekey
          type: string
          x-stoplight:
            id: rauhsewht9qkq
        userName:
          description: this is user who is updating the delegation
          type: string
          x-stoplight:
            id: 6figb1cav109o
        name:
          description: name of delegate
          type: string
          x-stoplight:
            id: 15ym3yee41nl0
        delegateusername:
          description: this is the user who should be assigned as the delegate of
            the parent use
          type: string
          x-stoplight:
            id: kba006ufar4dy
        delegatestartdate:
          description: in format MMDDYYYY
          type: string
          x-stoplight:
            id: bn1i05twfri5v
        delegateenddate:
          description: in format MMDDYYYY
          type: string
          x-stoplight:
            id: 7r3gxhcrq3477
        parentusername:
          description: "this is the parent username, if not passed it will consider\
            \ userName as parentusername"
          type: string
          x-stoplight:
            id: vv77oo1e2dj1k
        description:
          type: string
          x-stoplight:
            id: s2yc7c2jlywbg
      required:
      - delegateenddate
      - delegatestartdate
      - delegateusername
      - key
      - name
      - userName
      title: EditDelegateRequest
      x-stoplight:
        id: 1cejr83h2s5a4
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
x-stoplight:
  id: 11gpcfoz001w2
